use prefetch

diff --git a/.github/workflows/npm-deps-hash.yml b/.github/workflows/npm-deps-hash.yml
--- a/.github/workflows/npm-deps-hash.yml
+++ b/.github/workflows/npm-deps-hash.yml
@@ -22,18 +22,16 @@ jobs:
       - name: Generate npmDepsHash
         id: hash
         run: |
-          sed -i 's/npmDepsHash = ".*";/npmDepsHash = "";/' flake.nix
-          cat flake.nix
-          nix build .#default 2>&1 | grep -oP 'got:\s*\Ksha256-[A-Za-z0-9+/=]+'
-          nix build .#default 2>&1 | grep -oP 'got:\s*\Ksha256-[A-Za-z0-9+/=]+' || true
-          # Attempt to build and extract the correct hash from the error message
-          NEW_HASH=$(nix build .#default 2>&1 | grep -oP 'got:\s*\Ksha256-[A-Za-z0-9+/=]+' || true)
-          cat flake.nix
-          if [ -z "$NEW_HASH" ]; then
-            echo "Error: Could not extract new hash."
-            exit 1
-          fi
-          echo "new_hash=$NEW_HASH" >> $GITHUB_OUTPUT
+            # Fetch the correct npmDepsHash using prefetch-npm-deps
+            NEW_HASH=$(nix-shell -p prefetch-npm-deps --run 'prefetch-npm-deps package-lock.json' | tail -n1)  
+            echo "hash"
+            echo $NEW_HASH
+            if [ -z "$NEW_HASH" ]; then
+              echo "Error: Could not extract new hash."
+              exit 1
+            fi
+  
+            echo "new_hash=$NEW_HASH" >> $GITHUB_OUTPUT
 
       - name: Update flake.nix
         run: |
